language: scala

scala:
   - 2.12.2

jdk:
  - oraclejdk8

script:
  - sbt 'testOnly Puzzle01Spec'

addons:
  code_climate:
    repo_token: 99ca8eebe792957479f1daa885a007451e7ec724526c542d0fc7e217c22391a9
