language: scala

scala:
   - 2.11.7

script:
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

addons:
  code_climate:
    repo_token: 6f130a17e8fffbe16c094e81998b552492a72dff8b818056df3973dda43476e9

script:
  ### Script to build Ionesco #################################################
  - sbt clean coverage test
    # remove SBT lockfile and Ivy properties so they don't get cached
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  ### Report test coverage ####################################################
  - sbt coverageReport     # generate Cobertura coverage report
  - sbt coverageAggregate  # aggregate coverage reports from subproject
